// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8KHuLNsH6kIhvrZvSGw_f0FJF8nI5GnA',
    appId: '1:1050359858091:web:7160416f21eae313cac8ee',
    messagingSenderId: '1050359858091',
    projectId: 'neelam-8f27b',
    authDomain: 'neelam-8f27b.firebaseapp.com',
    storageBucket: 'neelam-8f27b.firebasestorage.app',
    measurementId: 'G-9KEKPE13C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkn0fVKkpOvp6oMy0A9TFfZZRXCaOhwg',
    appId: '1:1050359858091:android:a8728b001071a6c5cac8ee',
    messagingSenderId: '1050359858091',
    projectId: 'neelam-8f27b',
    storageBucket: 'neelam-8f27b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV9FaUyosV471Gz_gXjGuQudKAUbIyJZ4',
    appId: '1:1050359858091:ios:99fe2f3ea1dbbcc9cac8ee',
    messagingSenderId: '1050359858091',
    projectId: 'neelam-8f27b',
    storageBucket: 'neelam-8f27b.firebasestorage.app',
    iosBundleId: 'com.example.neelamRajpoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV9FaUyosV471Gz_gXjGuQudKAUbIyJZ4',
    appId: '1:1050359858091:ios:99fe2f3ea1dbbcc9cac8ee',
    messagingSenderId: '1050359858091',
    projectId: 'neelam-8f27b',
    storageBucket: 'neelam-8f27b.firebasestorage.app',
    iosBundleId: 'com.example.neelamRajpoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8KHuLNsH6kIhvrZvSGw_f0FJF8nI5GnA',
    appId: '1:1050359858091:web:76cf5b5e1214e4ddcac8ee',
    messagingSenderId: '1050359858091',
    projectId: 'neelam-8f27b',
    authDomain: 'neelam-8f27b.firebaseapp.com',
    storageBucket: 'neelam-8f27b.firebasestorage.app',
    measurementId: 'G-1TR5B1RNE8',
  );
}
